replicaCount: 2

image:
  repository: prasanna-konduri/learner-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 30080

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

labels:
  app: frontend

ports:
  containerPort: 3000
